# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_time_remaining <- function(step, is_lower, is_final_age) {
    .Call(`_smallpopn_make_time_remaining`, step, is_lower, is_final_age)
}

microsim_inner <- function(initial_popn, fertility_rates, mortality_rates, n_age, n_sex, n_period, step, i_dom_sex) {
    .Call(`_smallpopn_microsim_inner`, initial_popn, fertility_rates, mortality_rates, n_age, n_sex, n_period, step, i_dom_sex)
}

